---
config:
  kmsKeyId: arn:aws:kms:us-east-1:338257455868:key/addc93b9-7866-4de9-b8c1-bc20ed63445d

  environment:
    auth:
      ENC_SECRET: AQECAHiz6EAWjwTvKZjeuwEMbCwBVh0SD6oQMVSyLS55+XQYLAAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNMjGf37py07am/ynAIBEIAp6L/dAdKiAG5stE03TlwUrE/LmIzZCX32VvPh12I9S7pL01xEn1arll0=
      
    common:
      ENC_MESSAGE: AQECAHiz6EAWjwTvKZjeuwEMbCwBVh0SD6oQMVSyLS55+XQYLAAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCEt/8cgCpGViclzXQIBEIAmWjNKMDjyb/qRdnOraGPiCG/tgBDN61LgO7FQIqU4IgjYfsblg8k=
