---
config:
  kmsKeyId: arn:aws:kms:us-east-1:338257455868:key/cdae88a3-8653-4b8e-a7f2-84a95e3da24b

  environment:
    auth:
      ENC_SECRET: AQECAHiM+3XXQCdXEghU4IGojIlHC7swVnewSs8sqQpvxTG1bQAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDC0JXqlNK6hdhaORIAIBEIApSC2Izl/LW4iv73140BuC14JinHP8X2wYME/6VK3Rr8HQlDL/oHDl9jw=
      
    common:
      EVENT_STREAM_TABLE: eventsStream-dan
      ENC_MESSAGE: AQECAHiz6EAWjwTvKZjeuwEMbCwBVh0SD6oQMVSyLS55+XQYLAAAAGkwZwYJKoZIhvcNAQcGoFowWAIBADBTBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDCEt/8cgCpGViclzXQIBEIAmWjNKMDjyb/qRdnOraGPiCG/tgBDN61LgO7FQIqU4IgjYfsblg8k=
