---
config:
  kmsKeyId: arn:aws:kms:us-east-1:338257455868:key/36673e22-601f-4a34-8dd0-9788e86a5ece

  environment:
    auth:
      ENC_SECRET: AQECAHgpROqx3FzArQe30Du14vHyOddV8gfyFrhl/4ppy/+KUAAAAGwwagYJKoZIhvcNAQcGoF0wWwIBADBWBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDP/WIHoxaRhDKBiDUwIBEIAp4/BlF6twUUNEVr401l2XcRMMSgffXTA4L0A4ICGS6OElai5p4X0VM5U=
      
    common:
      SERVICE_STAGE: dan
      EVENT_STREAM_TABLE: eventStreamTable-dan
      AGGREGATE_TABLE: aggregateTable-dan
      AGGREGATE_GSI: NameId
