Description: "KMS infrastructure of A Cloud Guru"
Parameters:
  Stage:
    Description: "Stage Name"
    Type: String
    AllowedPattern: ^[a-z]+$
  IAMUserName:
    Description: "IAM User Name"
    Type: String
    AllowedPattern: ^[a-z\-]+$

Resources:
  EnvVarKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/school-env-vars-${Stage}
      TargetKeyId:
        Ref: EnvVarKey

  EnvVarKey:
    Type: AWS::KMS::Key
    Properties:
      Description: "The key used to encrypt and decrypt env vars"
      KeyPolicy:
        Version: "2012-10-17"
        Id: "school-env-vars-key-policy"
        Statement:
          - Sid: "Enable IAM User Permissions"
            Effect: "Allow"
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Action:
              - "kms:*"
            Resource: "*"
          - Sid: "Allow access for Key Administrators"
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/daniel
            Action:
              - "kms:Create*"
              - "kms:Describe*"
              - "kms:Enable*"
              - "kms:List*"
              - "kms:Put*"
              - "kms:Update*"
              - "kms:Revoke*"
              - "kms:Disable*"
              - "kms:Get*"
              - "kms:Delete*"
              - "kms:ScheduleKeyDeletion"
              - "kms:CancelKeyDeletion"
              - "kms:TagResource"
              - "kms:UntagResource"
            Resource: "*"
          - Sid: "Allow use of the key"
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/${IAMUserName}
                - !Sub arn:aws:iam::${AWS::AccountId}:role/quick-roster-${Stage}-us-east-1-lambdaRole
            Action:
              - "kms:Encrypt"
              - "kms:Decrypt"
              - "kms:ReEncrypt*"
              - "kms:GenerateDataKey*"
              - "kms:DescribeKey"
            Resource: "*"
          - Sid: "Allow attachment of persistent resources"
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:user/${IAMUserName}
                - !Sub arn:aws:iam::${AWS::AccountId}:role/quick-roster-${Stage}-us-east-1-lambdaRole
            Action:
              - "kms:CreateGrant"
              - "kms:ListGrants"
              - "kms:RevokeGrant"
            Resource: "*"
            Condition:
              Bool:
                kms:GrantIsForAWSResource: "true"
Outputs:
  EnvVarKeyArn:
    Description: "Key Arn"
    Value: !Sub ${EnvVarKey.Arn}
